sonar.projectKey=polinakupreychuk_Diplom
sonar.organization=polinakupreychuk
sonar.projectName=Media Data Analysis Platform
sonar.projectVersion=0.1.0

sonar.sources=app,components,lib
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/public/**,**/*.config.*,**/*.d.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/tests/**,**/*.config.*,components/ui/**,components/dashboard/**,components/feed/**,components/page-header.tsx,components/sidebar.tsx,components/theme-provider.tsx,app/api/**,lib/use-articles.ts,lib/nlp-utils.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8