sonar.projectKey=polinakupreychuk_Diplom
sonar.organization=polinakupreychuk
sonar.projectName=Media Data Analysis Platform
sonar.projectVersion=0.1.0
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.ts,**/*.spec.ts,.next/**,coverage/**,public/**
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.scm.disabled=true